
server:
  port: 8080
spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
      jakarta:
        persistence:
          sharedCache: mode
  
  application:
    name: profile-application
  
  datasource:
    url: jdbc:h2:file:./db/profileDB
    # url: jdbc:h2:mem:testDB
    username: user
    password: pass
    driver-class-name: org.h2.Driver  
    
    hikari:
      maximum-pool-size: 10
  h2:
    console:
      enabled: true
      path: /database
  security:
    oauth2:
      resouceserver:
        jwt:
############
config:
  cors:
    front: http://127.0.0.1:5173/
##########
key:
  location: /keys/key-jwt.pub